name: Backup Main Branch on Push

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create backup branch
        run: |
          git checkout -b backup-main-$(date +%Y%m%d%H%M%S)
          git push origin backup-main-$(date +%Y%m%d%H%M%S)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
