name: Format Python code

on:
  push:
    branches:
      - main
  workflow_dispatch:
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install isort and black
        run: pip install isort black

      - name: Run isort
        run: isort . --profile="black" --lines-after-imports=2

      - name: Run black
        run: black .

      - name: Get commit details
        id: commit-details
        run: |
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ steps.commit-details.outputs.hash }}) GHA isort and black formatting"
          title: "${{ steps.commit-details.outputs.hash }}) GHA isort and black formatting"
          body: "This PR applies isort and black formatting to the Python code."
          branch: "formatting-changes-${{ steps.commit-details.outputs.hash }}"
          base: "main"
          labels: "formatting"
